//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLReader
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.QUESTIONs = new HashSet<QUESTION>();
            this.USER_ANSWER = new HashSet<USER_ANSWER>();
        }
    
        [Display(Name = "UserName", Description = "Unique identifier of a user", ShortName = "uname")]
        public string UNAME { get; set; }
        [Display(Name = "Password", Description = "Allows for user authentification", ShortName = "passw")]
        public string PASSW_HASH { get; set; }
        public string SALT { get; set; }
        [Display(Name = "First Name", Description = "User's first name", ShortName = "fname")]
        public string FNAME { get; set; }
        [Display(Name = "Last Name", Description = "User's last name", ShortName = "lname")]
        public string LNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTION> QUESTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ANSWER> USER_ANSWER { get; set; }
    }
}
