//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION()
        {
            this.USER_ANSWER = new HashSet<USER_ANSWER>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string AUTHOR { get; set; }
        public string OPT_A { get; set; }
        public string OPT_B { get; set; }
        public string OPT_C { get; set; }
        public string OPT_D { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_ANSWER> USER_ANSWER { get; set; }
    }
}
