CREATE TABLE [dbo].[USER]
(
	[UNAME] VARCHAR(20) NOT NULL PRIMARY KEY,
	[PASSW_HASH] VARCHAR(255) NOT NULL,
	[SALT] VARCHAR(255) NOT NULL,

	[FNAME] VARCHAR(30) NOT NULL,
	[LNAME] VARCHAR(30) NOT NULL
);

CREATE TABLE [dbo].[CATEGORY]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,

	[TITLE] VARCHAR(20) NOT NULL,
	[DESCRIPTION] VARCHAR(150)
);

CREATE TABLE [dbo].[QUESTION]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[TITLE] VARCHAR(150) NOT NULL,

	[CATEGORY_ID] INT
	FOREIGN KEY REFERENCES [CATEGORY](ID)
	ON DELETE CASCADE,

	[AUTHOR] VARCHAR(20)
	FOREIGN KEY REFERENCES [USER](UNAME)
	ON DELETE SET NULL,

	[OPT_A] VARCHAR(50) NOT NULL,
	[OPT_B] VARCHAR(50) NOT NULL,
	[OPT_C] VARCHAR(50) NOT NULL,
	[OPT_D] VARCHAR(50) NOT NULL
);

CREATE TABLE [dbo].[USER_ANSWER]
(
	[UNAME] VARCHAR(20)
	FOREIGN KEY REFERENCES [USER](UNAME)
	ON DELETE SET NULL,

	[QUES_ID] INT NOT NULL
	FOREIGN KEY REFERENCES [QUESTION](ID)
	ON DELETE CASCADE,

	[CORR_ANS] BIT NOT NULL
);
