CREATE TABLE [dbo].[QUESTION]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[TITLE] VARCHAR(150) NOT NULL,

	[CATEGORY_ID] INT,

	[AUTHOR] VARCHAR(20) FOREIGN KEY REFERENCES [USER](UNAME),

	[OPT_A] VARCHAR(50) NOT NULL,
	[OPT_B] VARCHAR(50) NOT NULL,
	[OPT_C] VARCHAR(50) NOT NULL,
	[OPT_D] VARCHAR(50) NOT NULL
);