CREATE TABLE [dbo].[QUESTION]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[TITLE] VARCHAR(150) NOT NULL,

	[CATEGORY_ID] INT
	FOREIGN KEY REFERENCES [CATEGORY](ID)
	ON DELETE CASCADE,

	[AUTHOR] VARCHAR(20)
	FOREIGN KEY REFERENCES [USER](UNAME)
	ON DELETE SET NULL,

	[OPT_A] VARCHAR(50) NOT NULL,
	[OPT_B] VARCHAR(50) NOT NULL,
	[OPT_C] VARCHAR(50) NOT NULL,
	[OPT_D] VARCHAR(50) NOT NULL
);