CREATE TABLE [dbo].[USER_ANSWER]
(
	[UNAME] VARCHAR(20)
	FOREIGN KEY REFERENCES [USER](UNAME)
	ON DELETE SET NULL,

	[QUES_ID] INT NOT NULL
	FOREIGN KEY REFERENCES [QUESTION](ID)
	ON DELETE CASCADE,

	[CORR_ANS] BIT NOT NULL
);