CREATE TABLE [dbo].[USER]
(
	[UNAME] VARCHAR(20) NOT NULL PRIMARY KEY,
	[PASSW_HASH] VARCHAR(255) NOT NULL,
	[SALT] VARCHAR(255) NOT NULL,

	[FNAME] VARCHAR(30) NOT NULL,
	[LNAME] VARCHAR(30) NOT NULL
)